import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sandeep yadav",
  description: "Generated by Sandeep yadav",
  authors: [
    {
      name: "Sandeep yadav",
    },
  ],
  category: "Personal",
  keywords: ["Sandeep yadav"],
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://sandeep-yadav.vercel.app",
    siteName: "Sandeep yadav",
    title: "Sandeep yadav",
    images: [
      {
        url: "https://yadav.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Frao.f0087b7a.jpeg&w=3840&q=75",
        width: 800,
        height: 600,
        alt: "Sandeep yadav",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
